# action.yml
name: 'GitHub Release: Next Semver'
description: 'Get the next valid GitHub release semver value'
inputs:
  token:
    description: 'GitHub platform token'
    required: true
  use_tag_name:
    description: 'Should we use the tag name instead of the release name'
    required: true
    default: true
  strip_tag_prefix:
    description: 'A prefix we should strip away'
    required: false
    default: 'v'
  override_repo:
    description: 'GitHub repo context to use instead of the current one (username/reponame)'
    required: false
  type:
    description: 'What semver bump type is this (auto, major, premajor, minor, preminor, patch, prepatch, or prerelease)'
    required: true
    default: 'major'
outputs:
  current:
    description: 'the current semver'
  type:
    description: 'the semver change type'
  next:
    description: 'the next semver'
runs:
  using: 'node12'
  main: 'dist/index.js'
